name: Dialoguetest
version: 0.0.1
author: GamingSnail7410
main: GamingSnail7410\Dialoguetest\Main
api: 3.21.1
mcpe-protocol: 448
description: A dialogue test plugin for npcs.

commands:
  npc1:
    description: This is dialogue 1
    aliases: npc1
    permission: npc1.command
  npc2:
    description: This is dialogue 2
    aliases: npc2
    permission: npc2.command
  npc3:
    description: This is dialogue 3
    aliases: npc3
    permission: npc3.command
  npc4:
    description: This is dialogue 4
    aliases: npc4
    permission: npc4.command
permissions:
  npc1.command:
    description: This is dialogue 1 permission
    default: op
  npc2.command:
    description: This is dialogue 2 permission
    default: op
  npc3.command:
    description: This is dialogue 3 permission
    default: op
  npc4.command:
    description: This is dialogue 4 permission
    default: op
